name: Android Release APK

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Decode keystore
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        run: |
          mkdir -p keystore
          echo "$ANDROID_KEYSTORE_BASE64" | base64 -d > keystore/flightsearch-release.jks

      - name: Configure gradle.properties
        env:
          RELEASE_STORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_ALIAS_PASSWORD }}
        run: |
          echo "RELEASE_STORE_FILE=keystore/flightsearch-release.jks" >> gradle.properties
          echo "RELEASE_STORE_PASSWORD=${RELEASE_STORE_PASSWORD}" >> gradle.properties
          echo "RELEASE_KEY_ALIAS=${RELEASE_KEY_ALIAS}" >> gradle.properties
          echo "RELEASE_KEY_PASSWORD=${RELEASE_KEY_PASSWORD}" >> gradle.properties
          echo "APP_VERSION_CODE=${{ github.run_number }}" >> gradle.properties
          echo "APP_VERSION_NAME=${{ github.ref_name || '1.0.' }}${{ github.run_number }}" >> gradle.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew || true

      - name: Build release APK
        run: ./gradlew assembleRelease --stacktrace

      - nam
